Lesson 1 completed
SergeiButchak/Django_GB pull request #1
Opened 2021-06-26 07:27 UTC by SergeiButchak

Не заню насколько правильно так делать, но репозиторий развернул в папке geekshop, а не в geekshop-server

2021-06-27 15:44 UTC, Vokler requested changes
У вас файл README в каталоге geekshop, а должен быть в корне рпепозитория

2021-06-27 15:44 UTC, Vokler commented on geekshop/settings.py
> +    BASE_DIR / 'static',
Если используете список , то запятая не нужна

2021-06-29 06:00 UTC, SergeiButchak commented on geekshop/settings.py
> +    BASE_DIR / 'static',
Еще на основах по пайтану нам говорили, что при многострочной записи принято  после последнего элемента оставлять запятую, неважно список это, кортеж или словарь. То же самое я вижу в сторонних бибилиотеках и фреймворках, в том же джанго urlpatterns из коробки выглядит так
urlpatterns = [
    path('admin/', admin.site.urls),
]

2021-06-29 06:25 UTC, Vokler commented on geekshop/settings.py
> +    BASE_DIR / 'static',
Хорошо, тогда оставляем)

2021-06-29 06:26 UTC, Vokler approved these changes

2021-06-29 06:26 UTC, merged